FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    access_type: public_method

    properties:
        id:
            expose: true
            read_only: true
            groups: [userList, userDetails]

        username:
            expose: true
            groups: [userList, userDetails]

        email:
            expose: true
            groups: [userDetails]

        groups:
            expose: true
            read_only: true
            groups: [userList, userDetails]