FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    access_type: public_method

    properties:
        id:
            expose: true
            read_only: true
            groups: [list, details]

        username:
            expose: true
            groups: [list, details]

        email:
            expose: true
            groups: [owner, ROLE_ADMIN]

        roles:
            expose: true
            groups: [details]