parameters:
#    gearbox_security.example.class: Gearbox\SecurityBundle\Example

services:
#    gearbox_security.example:
#        class: %gearbox_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

